# docker-compose.yml
version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: example

  lighthouse:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    environment:
      PGHOST: db
      PGUSER: dbuser
      PGPASSWORD: example
      LAS_PORT: 4008
      LAS_CORS: true
    ports:
      - '4008:4008'
    volumes:
      - ./src:/home/node/app/src
      - ./tsconfig.json:/home/node/app/tsconfig.json
      - ./nodemon.json:/home/node/app/nodemon.json
